### ISSUE TITLE
Button is clickable even when disabled

### ISSUE THREAD

**Issue by Deewens** [dkreider/ngx-loading-buttons#1]
Hi,

Thanks for your lib', however, I have a minor issue. When I use the [disabled] attribute on my button, with your library, (so with [mtBasicSpinner] and [hideText], even when the button should be disabled we can still click on it and the button still fires an event). However, it works well when I remove the attribute from your libs.

The fix should be: when the button is marked as [disabled]="true", the click should not be fired.

Thanks!

**Comment by dkreider** [comment]
Hey @Deewens 👋🏻 

Thanks for opening this issue. I'll investigate and push a fix as soon as I get time.

**Comment by dkreider** [comment]
@Deewens what version of Angular are you using?

**Comment by MilanNemeth** [comment]
hey @dkreider,

Since this issue is still open, can you tell me if it's or it isn't resolved in the latest release? Btw, I've found that it's still reproducible.
TY

**Comment by Deewens** [comment]
> @Deewens what version of Angular are you using?

Hi, sorry, I completely forgot to answer. I'm using Angular 13.

**Comment by MilanNemeth** [comment]
> > @Deewens what version of Angular are you using?
> 
> Hi, sorry, I completely forgot to answer. I'm using Angular 13.

Ditto

**Comment by dkreider** [comment]
Hey folks, thanks for your interest. I'll try to push a fix soon.

**Comment by dkreider** [comment]
@Deewens or @MilanNemeth 

Been trying to reproduce this issue on Angular 13 but no success at all.

Could one of you throw a demo Angular project with this issue into a repo and share the link, please?

Thanks.

**Comment by Deewens** [comment]
I can do that that during the week or probably next week.

**Comment by MilanNemeth** [comment]
Hi @dkreider 
Sorry, I won't have time to build a demo, but I have a slight hint for you.
I've only experienced the issue, when the component was being used in views wrapped inside a [mat-sidenav](https://material.angular.io/components/sidenav/overview). Otherwise, it was working fine.
Finally, I had to make my own custom component due to hurry, and it had the same issue. 
I guess it's related to event bubbling, and I solved the issue by linking the inner button's click event to a custom 'btnClick' @Output on my component, and I used this btnClick EventEmitter for event binding from all the parent components.
Hope this helps...

**Comment by dkreider** [comment]
@MilanNemeth that's very helpful! I'll see if I can reproduce.

**Comment by rbalet** [comment]
@dkreider This issue can be easily reproduced in the angular 15 version.

```html
<button
  color="primary"
  mat-button
  (click)="uploadSettings()"
  [mtBasicSpinner]="service.loading$ | async"
  [disabled]="!isDirty"
>
  {{ 'SAVE' | translate }}
</button>
```

**Comment by rbalet** [comment]
@dkreider I had a look and you're using the following

```typescript
  @HostBinding('disabled')
  get disabled(): boolean {
    return this.mtBasicSpinner;
  }
```

Which make it obvious on the reason why this isn't working.
Would it be an Idea to just remove this one ? 

Idk if people want's their button to turn to gray when the loader is running.

**Comment by rbalet** [comment]
@dkreider Fixed by https://github.com/dkreider/ngx-loading-buttons/issues/1

**Comment by ab-spingo** [comment]
This is still an issue. As indicated in @rbalet comment, library overrides normal disabled behaviour.
Usecase: let's say you'd like to disable submit button on the registration form until agreements checkbox is checked and  show the spinner after clicking on active button until backend processes the request.

**Comment by ab-spingo** [comment]
Temporary solution: put a econd copy of a button and toggle their visibility:

`<button mat-flat-button color="primary" [disabled]="!FormModel.valid" *ngIf="!inProgress">Next</button>
<button mat-flat-button color="primary" [mtBasicSpinner]="inProgress" *ngIf="inProgress">Next</button>`

**Comment by dkreider** [comment]
Fixed with #24 and vs 17.0.2
